hwi_oauth:
  firewall_name: main
  resource_owners:
    google:
      type: google
      client_id: "%env(GOOGLE_CLIENT_ID)%"
      client_secret: "%env(GOOGLE_CLIENT_SECRET)%"
      scope: "email profile openid"
      options:
        access_type: offline
        approval_prompt: force
